In [40]:
import pandas as pd
import numpy as np
from pathlib import Path
import xml.etree.ElementTree as ET

# WP: Wahlperiode
# Quelle der Daten: 

In [53]:
DATA_PATH = Path('data')
MDB_XML_PATH = DATA_PATH / 'MDB_STAMMDATEN.XML'
DF_MDB_PATH = DATA_PATH / 'df_mdb.csv' #one row per individuum, one col per wp containing 0 / 1
DF_MDB_WP_PATH = DATA_PATH / 'df_mdb_wp.csv' # one row per individuum per wp, containting e.g. 12. so one abgeordneter who has been in parliament for several wp will receive one row per wp

# parse xml data into dataFrame / .csv fomat

In [42]:
def get_mdb_data(mdb_xml_path = MDB_XML_PATH):
    list_of_mdb = []
    MDB_STAMMDATEN = ET.parse(mdb_xml_path)
    root = MDB_STAMMDATEN.getroot()
    
    for mdb in root.findall('MDB'):
        mdb_dict = {}
        ID, NAMEN, BIOGRAFISCHE_ANGABEN, WAHLPERIODEN = mdb[0], mdb[1], mdb[2], mdb[3]

        mdb_dict['ID'] = ID.text
        mdb_dict['NACHNAME'] = NAMEN.find('NAME').find('NACHNAME').text  
        mdb_dict['VORNAME'] = NAMEN.find('NAME').find('VORNAME').text  

        #print(mdb.tag, mdb.text, mdb.findall('NACHNAME'))
        for element in BIOGRAFISCHE_ANGABEN:
            mdb_dict[element.tag] = element.text

        mdb_dict['ANZ_WAHLPERIODEN'] = len(list(WAHLPERIODEN))

        for wahlperiode in WAHLPERIODEN:
            mdb_dict[int(wahlperiode.find('WP').text)] = 1

        list_of_mdb.append(mdb_dict)
    return pd.DataFrame(list_of_mdb)

In [352]:
def get_mdb_wp_data(mdb_xml_path = MDB_XML_PATH):
    list_of_mdb = []
    MDB_STAMMDATEN = ET.parse(mdb_xml_path)
    root = MDB_STAMMDATEN.getroot()
    
    for mdb in root.findall('MDB'):
        mdb_dict = {}
        ID, NAMEN, BIOGRAFISCHE_ANGABEN, WAHLPERIODEN = mdb[0], mdb[1], mdb[2], mdb[3]

        mdb_dict['ID'] = ID.text
        mdb_dict['NACHNAME'] = NAMEN.find('NAME').find('NACHNAME').text  
        mdb_dict['VORNAME'] = NAMEN.find('NAME').find('VORNAME').text  

        #print(mdb.tag, mdb.text, mdb.findall('NACHNAME'))
        for element in BIOGRAFISCHE_ANGABEN:
            mdb_dict[element.tag] = element.text

        mdb_dict['ANZ_WAHLPERIODEN'] = len(list(WAHLPERIODEN))

        for wahlperiode in WAHLPERIODEN:
            # one seperate entry per wp
            mdb_dict = mdb_dict.copy()
            mdb_dict['WP']=int(wahlperiode.find('WP').text)
            list_of_mdb.append(mdb_dict)
    return pd.DataFrame(list_of_mdb)

In [358]:
df_mdb = get_mdb_data(MDB_XML_PATH)
print(df_mdb.shape)
df_mdb.head()

(4089, 34)


ID   NACHNAME    VORNAME GEBURTSDATUM  \
0  11000001    Abelein    Manfred   20.10.1930   
1  11000002  Achenbach      Ernst   09.04.1909   
2  11000003  Ackermann  Annemarie   26.05.1913   
3  11000004  Ackermann       Else   06.11.1933   
4  11000005       Adam     Ulrich   09.06.1950   

                                    GEBURTSORT  GEBURTSLAND STERBEDATUM  \
0                                    Stuttgart         None  17.01.2008   
1                                       Siegen         None  02.12.1991   
2                                   Parabutsch  Jugoslawien  18.02.1994   
3                                       Berlin         None  14.09.2019   
4  Teterow, Kr. Teterow, Bezirk Neubrandenburg         None        None   

  GESCHLECHT          FAMILIENSTAND     RELIGION  ...    2   12   13   14  \
0   männlich          keine Angaben   katholisch  ...  NaN  NaN  NaN  NaN   
1   männlich  verheiratet, 3 Kinder  evangelisch  ...  NaN  NaN  NaN  NaN   
2   weiblich  verheiratet, 5 Kinder   katholisch  ...  1.0  NaN  NaN  NaN   
3   weiblich                  ledig  evangelisch  ...  NaN  1.0  NaN  NaN   
4   männlich  verheiratet, 2 Kinder  evangelisch  ...  NaN  1.0  1.0  1.0   

    15   16   1  17  18  19  
0  NaN  NaN NaN NaN NaN NaN  
1  NaN  NaN NaN NaN NaN NaN  
2  NaN  NaN NaN NaN NaN NaN  
3  NaN  NaN NaN NaN NaN NaN  
4  1.0  1.0 NaN NaN NaN NaN  

[5 rows x 34 columns]

In [359]:
df_mdb_wp = get_mdb_wp_data()
print(df_mdb_wp.shape)

(11627, 16)


In [360]:
df_mdb_wp[df_mdb_wp.NACHNAME == 'Merkel']

ID NACHNAME VORNAME GEBURTSDATUM GEBURTSORT GEBURTSLAND  \
4588  11001478   Merkel  Angela   17.07.1954    Hamburg        None   
4589  11001478   Merkel  Angela   17.07.1954    Hamburg        None   
4590  11001478   Merkel  Angela   17.07.1954    Hamburg        None   
4591  11001478   Merkel  Angela   17.07.1954    Hamburg        None   
4592  11001478   Merkel  Angela   17.07.1954    Hamburg        None   
4593  11001478   Merkel  Angela   17.07.1954    Hamburg        None   
4594  11001478   Merkel  Angela   17.07.1954    Hamburg        None   
4595  11001478   Merkel  Angela   17.07.1954    Hamburg        None   
9794  11003591   Merkel   Petra   18.09.1947     Berlin        None   
9795  11003591   Merkel   Petra   18.09.1947     Berlin        None   
9796  11003591   Merkel   Petra   18.09.1947     Berlin        None   

     STERBEDATUM GESCHLECHT       FAMILIENSTAND     RELIGION  \
4588        None   weiblich         verheiratet  evangelisch   
4589        None   weiblich         verheiratet  evangelisch   
4590        None   weiblich         verheiratet  evangelisch   
4591        None   weiblich         verheiratet  evangelisch   
4592        None   weiblich         verheiratet  evangelisch   
4593        None   weiblich         verheiratet  evangelisch   
4594        None   weiblich         verheiratet  evangelisch   
4595        None   weiblich         verheiratet  evangelisch   
9794        None   weiblich  geschieden, 1 Kind  evangelisch   
9795        None   weiblich  geschieden, 1 Kind  evangelisch   
9796        None   weiblich  geschieden, 1 Kind  evangelisch   

                                  BERUF PARTEI_KURZ  \
4588  Bundeskanzlerin, Dipl.-Physikerin         CDU   
4589  Bundeskanzlerin, Dipl.-Physikerin         CDU   
4590  Bundeskanzlerin, Dipl.-Physikerin         CDU   
4591  Bundeskanzlerin, Dipl.-Physikerin         CDU   
4592  Bundeskanzlerin, Dipl.-Physikerin         CDU   
4593  Bundeskanzlerin, Dipl.-Physikerin         CDU   
4594  Bundeskanzlerin, Dipl.-Physikerin         CDU   
4595  Bundeskanzlerin, Dipl.-Physikerin         CDU   
9794          Kaufmännische Angestellte         SPD   
9795          Kaufmännische Angestellte         SPD   
9796          Kaufmännische Angestellte         SPD   

                                              VITA_KURZ  \
4588  1973 Abitur in Templin. Physikstudium Univ. Le...   
4589  1973 Abitur in Templin. Physikstudium Univ. Le...   
4590  1973 Abitur in Templin. Physikstudium Univ. Le...   
4591  1973 Abitur in Templin. Physikstudium Univ. Le...   
4592  1973 Abitur in Templin. Physikstudium Univ. Le...   
4593  1973 Abitur in Templin. Physikstudium Univ. Le...   
4594  1973 Abitur in Templin. Physikstudium Univ. Le...   
4595  1973 Abitur in Templin. Physikstudium Univ. Le...   
9794                                               None   
9795                                               None   
9796                                               None   

                          VEROEFFENTLICHUNGSPFLICHTIGES  ANZ_WAHLPERIODEN  WP  
4588  4 Funktionen in Körperschaften und Anstalten d...                 8  12  
4589  4 Funktionen in Körperschaften und Anstalten d...                 8  13  
4590  4 Funktionen in Körperschaften und Anstalten d...                 8  14  
4591  4 Funktionen in Körperschaften und Anstalten d...                 8  15  
4592  4 Funktionen in Körperschaften und Anstalten d...                 8  16  
4593  4 Funktionen in Körperschaften und Anstalten d...                 8  17  
4594  4 Funktionen in Körperschaften und Anstalten d...                 8  18  
4595  4 Funktionen in Körperschaften und Anstalten d...                 8  19  
9794                                               None                 3  15  
9795                                               None                 3  16  
9796                                               None                 3  17

# clean data

In [361]:
# ok, quite expected. some cleaning necessarry: 'BÜNDNIS 90/DIE GRÜNEN', 'DIE GRÜNEN/BÜNDNIS 90', 'GRÜNE'
for grünen_alias in ['BÜNDNIS 90/DIE GRÜNEN', 'DIE GRÜNEN/BÜNDNIS 90', 'GRÜNE']:
    df_mdb.replace(grünen_alias, 'DIE GRÜNEN', inplace=True)
    df_mdb_wp.replace(grünen_alias, 'DIE GRÜNEN', inplace=True)

# save as csv

In [362]:
df_mdb.to_csv(DF_MDB_PATH, index=None)
df_mdb_wp.to_csv(DF_MDB_WP_PATH, index=None)

# read in data. exploratory data analysis

In [363]:
df_mdb = pd.read_csv(DF_MDB_PATH, index_col=None)

In [364]:
df_mdb.columns

Index(['ID', 'NACHNAME', 'VORNAME', 'GEBURTSDATUM', 'GEBURTSORT',
       'GEBURTSLAND', 'STERBEDATUM', 'GESCHLECHT', 'FAMILIENSTAND', 'RELIGION',
       'BERUF', 'PARTEI_KURZ', 'VITA_KURZ', 'VEROEFFENTLICHUNGSPFLICHTIGES',
       'ANZ_WAHLPERIODEN', '5', '6', '7', '8', '9', '10', '11', '3', '4', '2',
       '12', '13', '14', '15', '16', '1', '17', '18', '19'],
      dtype='object')

In [365]:
df_mdb.tail()

ID  NACHNAME    VORNAME GEBURTSDATUM              GEBURTSORT  \
4084  11004958     Nölke   Matthias   08.01.1980                  Kassel   
4085  11004959    Martin   Dorothee   21.01.1978                     NaN   
4086  11004960    Wetzel   Wolfgang   11.05.1968                 Schlema   
4087  11004961  Natterer  Christian   19.02.1981  Tettnang / Deutschland   
4088  11004962    Dahmen    Janosch   06.09.1981                     NaN   

     GEBURTSLAND STERBEDATUM GESCHLECHT          FAMILIENSTAND  \
4084         NaN         NaN   männlich                  ledig   
4085         NaN         NaN   weiblich                    NaN   
4086         NaN         NaN   männlich  verheiratet, 2 Kinder   
4087         NaN         NaN   männlich    verheiratet, 1 Kind   
4088         NaN         NaN   männlich                    NaN   

                RELIGION  ...   2  12  13  14  15  16   1  17  18   19  
4084      konfessionslos  ... NaN NaN NaN NaN NaN NaN NaN NaN NaN  1.0  
4085                 NaN  ... NaN NaN NaN NaN NaN NaN NaN NaN NaN  1.0  
4086  römisch-katholisch  ... NaN NaN NaN NaN NaN NaN NaN NaN NaN  1.0  
4087  römisch-katholisch  ... NaN NaN NaN NaN NaN NaN NaN NaN NaN  1.0  
4088                 NaN  ... NaN NaN NaN NaN NaN NaN NaN NaN NaN  1.0  

[5 rows x 34 columns]

In [366]:
df_mdb_wp[['ID', 'PARTEI_KURZ']].groupby('PARTEI_KURZ').count().sort_values(by='ID', ascending=False).head(10)

ID
PARTEI_KURZ      
SPD          4250
CDU          4150
FDP          1036
CSU           993
DIE GRÜNEN    536
DIE LINKE.    297
AfD            90
PDS            77
Plos           41
DP             37

In [367]:
# wie - nur 2 Geschlechter? for the records: heute ist der 02.05.2021
df_mdb_wp[['ID', 'GESCHLECHT']].groupby('GESCHLECHT').count().sort_values(by='ID', ascending=False).head()

ID
GESCHLECHT      
männlich    9382
weiblich    2245

In [368]:
# auch hier: such diversity. wow
df_mdb_wp[['ID', 'RELIGION']].groupby('RELIGION').count().sort_values(by='ID', ascending=False).head(n=16)

ID
RELIGION                       
evangelisch                3406
ohne Angaben               3275
katholisch                 2985
römisch-katholisch          831
evangelisch-lutherisch      366
konfessionslos              234
evangelisch-reformiert       34
Atheistin                    12
Islam                         9
religionslos                  9
evangelisch-freikirchlich     9
freireligiös                  8
muslimisch                    7
Atheist                       6
griechisch-orthodox           1
neuapostolisch                1

In [369]:
# jetzt wirds richtig vielseitig. so viele Busfahrer und Krankenschwestern!
df_mdb_wp[['ID', 'BERUF']].groupby('BERUF').count().sort_values(by='ID', ascending=False).head(16).head(16)

ID
BERUF                      
Rechtsanwalt            567
Geschäftsführer         223
Landwirt                212
Angestellter            190
Rechtsanwalt und Notar  126
Journalist              117
Dipl.-Ingenieur         109
Kaufmann                104
Jurist                  102
Dipl.-Volkswirt         101
Hausfrau                100
Bundesminister a. D.     95
Gewerkschaftssekretär    94
Redakteur                76
Oberstudienrat a. D.     56
Rechtsanwältin           55

In [370]:
# gehen sie weiter. hier gibt es kein Klischee zu erkennen!
df_mdb_wp[['ID', 'FAMILIENSTAND']].groupby('FAMILIENSTAND').count().sort_values(by='ID', ascending=False).head(16)

ID
FAMILIENSTAND              
verheiratet, 2 Kinder  2726
verheiratet, 3 Kinder  1816
verheiratet            1720
verheiratet, 1 Kind    1365
keine Angaben          1043
verheiratet, 4 Kinder   891
ledig                   424
verheiratet, 5 Kinder   329
verheiratet, 6 Kinder   178
2 Kinder                113
verwitwet, 2 Kinder      77
1 Kind                   76
geschieden, 2 Kinder     71
geschieden, 1 Kind       69
verwitwet                63
3 Kinder                 50

In [371]:
# deleteme
start_date=16
end_date=18
#wps = range(start_date, end_date)
#selected_df = pd.concat([df_mdb[df_mdb[str(i)] == 1] for i in range(start_date,end_date+1)]).drop_duplicates()# deleteme
selected_df = df_mdb_wp[(df_mdb_wp['WP']>= start_date) & (df_mdb_wp['WP']<= end_date)].sort_values(by='VEROEFFENTLICHUNGSPFLICHTIGES')
selected_df.head()

ID  NACHNAME   VORNAME GEBURTSDATUM      GEBURTSORT GEBURTSLAND  \
11306  11004450      Zech    Tobias   09.07.1981       Trostberg        None   
10950  11004229  Reinhold     Hagen   23.03.1978          Wismar        None   
10491  11004004     Aumer     Peter   17.04.1976      Regensburg        None   
10886  11004179     Vogel  Johannes   29.04.1982  Wermelskirchen        None   
11171  11004371   Paschke    Markus   08.06.1963          Bremen        None   

      STERBEDATUM GESCHLECHT          FAMILIENSTAND            RELIGION  \
11306        None   männlich  verheiratet, 2 Kinder  römisch-katholisch   
10950        None   männlich               3 Kinder      konfessionslos   
10491        None   männlich                  ledig  römisch-katholisch   
10886        None   männlich            verheiratet         evangelisch   
11171        None   männlich            verheiratet        ohne Angaben   

                                           BERUF PARTEI_KURZ  \
11306                            Geschäftsführer         CSU   
10950  Meister im Maurer- und Betonbauerhandwerk         FDP   
10491                    Dipl.-Betriebswirt (FH)         CSU   
10886                     Politikwissenschaftler         FDP   
11171                      Gewerkschaftssekretär         SPD   

                                               VITA_KURZ  \
11306  1994/98 Wirtschaftsschule Mühldorf. 1998/2000 ...   
10950  1994/97 Ausbildung zum Maurer und Betonbauer, ...   
10491  Berufsausbildung zum Steuerfachgehilfen. Studi...   
10886  2001 Abitur am Städtischen Gymnasium Wermelski...   
11171  Gymnasium in Bremen. 1980/83 Ausbildung zum In...   

                           VEROEFFENTLICHUNGSPFLICHTIGES  ANZ_WAHLPERIODEN  WP  
11306  1 Berufliche Tätigkeit vor der Mitgliedschaft ...                 2  18  
10950  1 Berufliche Tätigkeit vor der Mitgliedschaft ...                 2  17  
10491  1 Berufliche Tätigkeit vor der Mitgliedschaft ...                 2  17  
10886  1 Berufliche Tätigkeit vor der Mitgliedschaft ...                 2  17  
11171  1 Berufliche Tätigkeit vor der Mitgliedschaft ...                 2  18

In [372]:
# deleteme
# keep occurences
NUM_DIM_KEEP = 8
values_to_keep = selected_df[['ID', 'FAMILIENSTAND']].groupby('FAMILIENSTAND').count().sort_values(by='ID', ascending=False).index[NUM_DIM_KEEP:2*NUM_DIM_KEEP]
values_to_keep

Index(['geschieden, 2 Kinder', '1 Kind', 'ledig, 1 Kind',
       'verheiratet, 5 Kinder', '3 Kinder', 'geschieden, 1 Kind', '4 Kinder',
       'geschieden, 3 Kinder'],
      dtype='object', name='FAMILIENSTAND')

In [373]:
levels = [values_to_keep, range(start_date, end_date+1)]
levels

[Index(['geschieden, 2 Kinder', '1 Kind', 'ledig, 1 Kind',
        'verheiratet, 5 Kinder', '3 Kinder', 'geschieden, 1 Kind', '4 Kinder',
        'geschieden, 3 Kinder'],
       dtype='object', name='FAMILIENSTAND'),
 range(16, 19)]

In [374]:
new_index = pd.MultiIndex.from_product(levels, names=['FAMILIENSTAND', 'WP'])
new_index

MultiIndex([( 'geschieden, 2 Kinder', 16),
            ( 'geschieden, 2 Kinder', 17),
            ( 'geschieden, 2 Kinder', 18),
            (               '1 Kind', 16),
            (               '1 Kind', 17),
            (               '1 Kind', 18),
            (        'ledig, 1 Kind', 16),
            (        'ledig, 1 Kind', 17),
            (        'ledig, 1 Kind', 18),
            ('verheiratet, 5 Kinder', 16),
            ('verheiratet, 5 Kinder', 17),
            ('verheiratet, 5 Kinder', 18),
            (             '3 Kinder', 16),
            (             '3 Kinder', 17),
            (             '3 Kinder', 18),
            (   'geschieden, 1 Kind', 16),
            (   'geschieden, 1 Kind', 17),
            (   'geschieden, 1 Kind', 18),
            (             '4 Kinder', 16),
            (             '4 Kinder', 17),
            (             '4 Kinder', 18),
            ( 'geschieden, 3 Kinder', 16),
            ( 'geschieden, 3 Kinder', 17),
           

In [375]:
# deleteme
grouped = selected_df[['ID', 'WP', 'FAMILIENSTAND']].groupby(['FAMILIENSTAND', 'WP']).count()
grouped.head(16)

ID
FAMILIENSTAND      WP    
1 Kind             16   9
                   17   6
                   18  10
2 Kinder           16  13
                   17  16
                   18  18
3 Kinder           16   6
                   17   8
                   18   5
4 Kinder           16   4
                   17   5
                   18   3
5 Kinder           17   1
                   18   1
Lebensgemeinschaft 16   2
                   17   2

In [376]:
grouped = grouped.reindex(new_index, fill_value=0)
grouped

ID
FAMILIENSTAND         WP    
geschieden, 2 Kinder  16  10
                      17   9
                      18   9
1 Kind                16   9
                      17   6
                      18  10
ledig, 1 Kind         16   4
                      17   9
                      18  10
verheiratet, 5 Kinder 16   7
                      17   6
                      18   8
3 Kinder              16   6
                      17   8
                      18   5
geschieden, 1 Kind    16   5
                      17   5
                      18   4
4 Kinder              16   4
                      17   5
                      18   3
geschieden, 3 Kinder  16   3
                      17   3
                      18   4

In [377]:
grouped.reset_index(inplace=True)
grouped

FAMILIENSTAND  WP  ID
0    geschieden, 2 Kinder  16  10
1    geschieden, 2 Kinder  17   9
2    geschieden, 2 Kinder  18   9
3                  1 Kind  16   9
4                  1 Kind  17   6
5                  1 Kind  18  10
6           ledig, 1 Kind  16   4
7           ledig, 1 Kind  17   9
8           ledig, 1 Kind  18  10
9   verheiratet, 5 Kinder  16   7
10  verheiratet, 5 Kinder  17   6
11  verheiratet, 5 Kinder  18   8
12               3 Kinder  16   6
13               3 Kinder  17   8
14               3 Kinder  18   5
15     geschieden, 1 Kind  16   5
16     geschieden, 1 Kind  17   5
17     geschieden, 1 Kind  18   4
18               4 Kinder  16   4
19               4 Kinder  17   5
20               4 Kinder  18   3
21   geschieden, 3 Kinder  16   3
22   geschieden, 3 Kinder  17   3
23   geschieden, 3 Kinder  18   4

In [378]:
# deleteme
wps = sorted(list(set(grouped.WP)))
familienstands = list(set(grouped.FAMILIENSTAND))
traces_values = []


In [379]:
for familienstand in familienstands:
    trace = grouped[grouped['FAMILIENSTAND'] == familienstand].sort_values(by='WP').ID.values
    traces_values.append(trace)
traces_values

[array([ 4,  9, 10]),
 array([7, 6, 8]),
 array([5, 5, 4]),
 array([4, 5, 3]),
 array([6, 8, 5]),
 array([ 9,  6, 10]),
 array([10,  9,  9]),
 array([3, 3, 4])]

# quality checks

In [385]:
df_mdb_wp[(df_mdb_wp.WP==19) & (df_mdb_wp.PARTEI_KURZ == 'CDU')]

ID  NACHNAME             VORNAME GEBURTSDATUM  \
603    11000198    Bleser               Peter   23.07.1952   
1878   11000616   Fuchtel        Hans-Joachim   13.02.1952   
3351   11001074    Kauder              Volker   03.09.1949   
3952   11001278  Landgraf           Katharina   24.02.1954   
4595   11001478    Merkel              Angela   17.07.1954   
...         ...       ...                 ...          ...   
11596  11004924  Vieregge             Kerstin   06.09.1976   
11597  11004926     Vries           Christoph   04.12.1974   
11604  11004934  Wiesmann  Bettina Margarethe   20.10.1966   
11608  11004938   Ziemiak                Paul   06.09.1985   
11625  11004961  Natterer           Christian   19.02.1981   

                                          GEBURTSORT GEBURTSLAND STERBEDATUM  \
603                                     Brachtendorf        None        None   
1878                                  Sulz am Neckar        None        None   
3351                                      Hoffenheim        None        None   
3952   Kirchengel / Krs Sondershausen, Bezirk Erfurt        None        None   
4595                                         Hamburg        None        None   
...                                              ...         ...         ...   
11596                                        Rinteln        None        None   
11597                                        Hamburg        None        None   
11604                                         Berlin        None        None   
11608                                        Stettin        None        None   
11625                         Tettnang / Deutschland        None        None   

      GESCHLECHT          FAMILIENSTAND                RELIGION  \
603     männlich  verheiratet, 3 Kinder      römisch-katholisch   
1878    männlich  verheiratet, 4 Kinder             evangelisch   
3351    männlich            verheiratet             evangelisch   
3952    weiblich  verheiratet, 4 Kinder  evangelisch-lutherisch   
4595    weiblich            verheiratet             evangelisch   
...          ...                    ...                     ...   
11596   weiblich                  ledig  evangelisch-reformiert   
11597   männlich  verheiratet, 3 Kinder      römisch-katholisch   
11604   weiblich  verheiratet, 4 Kinder  evangelisch-lutherisch   
11608   männlich  verheiratet, 2 Kinder      römisch-katholisch   
11625   männlich    verheiratet, 1 Kind      römisch-katholisch   

                                     BERUF PARTEI_KURZ  \
603                 Landwirtschaftsmeister         CDU   
1878                  Parl. Staatssekretär         CDU   
3351    Jurist, Vors. der CDU/CSU-Fraktion         CDU   
3952         Dipl.-Meliorationsingenieurin         CDU   
4595     Bundeskanzlerin, Dipl.-Physikerin         CDU   
...                                    ...         ...   
11596                       Betriebswirtin         CDU   
11597  Dipl.-Soziologe / ltd. Angestellter         CDU   
11604                Unternehmensberaterin         CDU   
11608               Angestellter / Student         CDU   
11625               Dipl.-Kaufmann (Univ.)         CDU   

                                               VITA_KURZ  \
603    1959/67 Volksschule. 1967/70 Ausbildung im elt...   
1878   Studium der Rechtswissenschaft und Wirtschafts...   
3351   Abitur 1969, Hegau-Gymnasium Singen. 1969/71 W...   
3952   1972 Abitur in Borna. 1972/76 Studium Meliorat...   
4595   1973 Abitur in Templin. Physikstudium Univ. Le...   
...                                                  ...   
11596  Realschule Extertal, Wirtschaftsabitur am Hans...   
11597  1994 Abitur an der katholischen Sankt-Ansgar-S...   
11604  1984 Abitur und Baccalauréat, Berlin. 1987 Dip...   
11608  1998 Eintritt in die Junge Union, seit 2001 Mi...   
11625  1992/98 Mittlere Reife am Bildungszentrum Bodn...   

                           VEROEFFENTLICHUNGSPFLICHTIGES  ANZ_WAHLPERIODEN  WP  
603

In [394]:
df_mdb_wp[(df_mdb_wp.PARTEI_KURZ == 'CSU')][['ID', 'BERUF']].groupby('BERUF').count().sort_values(by='ID', ascending=False).head(32)

ID
BERUF                                                  
Rechtsanwalt                                        116
Angestellter                                         19
Landwirt                                             19
Dipl.-Ingenieur (FH)                                 17
Dipl.-Agraringenieur                                 14
Jurist                                               13
Journalist                                           11
Präsident DBT a. D., Vizepräsident DBT a. D., I...   11
Müllermeister, Bundesminister für Wirtschaft un...   10
Diplom Kaufmann, Bundesminister a. D.                10
Rechtsanwalt, Bundesminister für Verkehr              9
Bäckermeister und Konditor, Parl. Staatssekretä...    9
Industriekaufmann                                     9
Ministerpräsident des Freistaates Bayern              9
Rechtsanwalt, Parl. Staatssekretär a. D.              9
Dipl.-Verwaltungswirt (FH), Bundesminister            8
Rechtsanwalt, Landgerichtsrat a. D., Bundesmini...    8
Geschäftsführer                                       8
Rechtsanwalt, Bundesbahndirektor a. D.                8
Industriekaufmann, Landwirt                           8
Dipl.-Ingenieur                                       8
Oberregierungsrat a. D. Bundesminister a.D.           8
Historiker                                            8
Vizepräsidentin DBT a. D., Dipl.-Volkswirtin, B...    8
Publizist, Parl. Staatssekretär a. D.                 8
Dipl.-Ökonom                                          8
Bundesminister a. D., Vizepräsident DBT a. D.         8
Bundesminister a. D., Rechtsanwalt                    8
Dipl.-Kaufmann, Oberpostdirektor a. D.                8
Baukaufmann, Parl. Staatssekretär a. D.               8
Dipl.-Verwaltungswirt, Industriekaufmann              8
Bundesminister a. D., Dipl.-Kaufmann, Müllermei...    8

In [387]:
df_mdb_wp[(df_mdb_wp.WP==18) & (df_mdb_wp.PARTEI_KURZ == 'CDU') & (df_mdb_wp.BERUF.str.contains('Bürgermeister'))]

ID     NACHNAME      VORNAME GEBURTSDATUM         GEBURTSORT  \
8903   11003035      Baumann       Günter   01.08.1947  Annaberg-Buchholz   
9406   11003264      Willsch  Klaus-Peter   28.02.1961     Bad Schwalbach   
9696   11003562       Kaster     Bernhard   01.11.1957              Trier   
10272  11003801      Liebing      Ingbert   11.05.1963          Flensburg   
10737  11004108    Mattfeldt      Andreas   28.09.1969     Verden (Aller)   
10793  11004135    Riebsamen       Lothar   24.09.1957    Schwäblishausen   
10818  11004146    Schnieder      Patrick   01.05.1968           Kyllburg   
10906  11004187        Weiss       Sabine   26.05.1958           Duisburg   
10991  11004262        Donth      Michael   08.06.1967          Metzingen   
11032  11004286        Haase    Christian   06.05.1966             Höxter   
11064  11004305  Hoppenstedt      Hendrik   14.06.1972      Großburgwedel   

      GEBURTSLAND STERBEDATUM GESCHLECHT          FAMILIENSTAND  \
8903         None        None   männlich  verheiratet, 2 Kinder   
9406         None        None   männlich  verheiratet, 5 Kinder   
9696         None        None   männlich  verheiratet, 2 Kinder   
10272        None        None   männlich  verheiratet, 2 Kinder   
10737        None        None   männlich  verheiratet, 2 Kinder   
10793        None        None   männlich  verheiratet, 2 Kinder   
10818        None        None   männlich            verheiratet   
10906        None        None   weiblich             geschieden   
10991        None        None   männlich  verheiratet, 3 Kinder   
11032        None        None   männlich    verheiratet, 1 Kind   
11064        None        None   männlich  verheiratet, 2 Kinder   

                     RELIGION  \
8903   evangelisch-lutherisch   
9406              evangelisch   
9696               katholisch   
10272  evangelisch-lutherisch   
10737                    None   
10793      römisch-katholisch   
10818      römisch-katholisch   
10906      römisch-katholisch   
10991      römisch-katholisch   
11032      römisch-katholisch   
11064             evangelisch   

                                                   BERUF PARTEI_KURZ  \
8903                Dipl.-Ingenieur, Bürgermeister a. D.         CDU   
9406                Dipl.-Volkswirt, Bürgermeister a. D.         CDU   
9696                                 Bürgermeister a. D.         CDU   
10272                                Bürgermeister a. D.         CDU   
10737                   Industriekaufmann, Bürgermeister         CDU   
10793                                Bürgermeister a. D.         CDU   
10818                                Bürgermeister a. D.         CDU   
10906  Rechtsanwältin, Bürgermeisterin a. D., Parl. S...         CDU   
10991                                Bürgermeister a. D.         CDU   
11032                                Bürgermeister a. D.         CDU   
11064  Bürgermeister a. D., Rechtsanwalt, Staatsminister         CDU   

                                               VITA_KURZ  \
8903                                                None   
9406   Abitur 1979 in Wiesbaden. 1980/86 Studium Volk...   
9696                                                None   
10272                                               None   
10737  1989 Abitur. 1992 Berufsausbildung Industrieka...   
10793  1967/74 Gymnasium Sigmaringen, Mittlere Reife....   
10818  1987 Abitur. 1987/88 Grundwehrdienst. 1988/95 ...   
10906  Bischöfliches Abteigymnasium und Leibniz-Gymna...   
10991  Grundwehrdienst in Dornstadt. Studium an der F...   
11032  Studium der Verwaltungswissenschaften, 1993 Ab...   
11064  1978/92 Schulbesuche in Thönse, Großburgwedel ...   

                           VEROEFFENTLICHUNGSPFLICHTIGES  ANZ_WAHLPERIODEN  WP  
8903                                                None                 5  18  
9406   2 Entgeltliche Tätigkeiten neben dem Mandat: \...                 6  18  
9696                                                None 